--- 
title: "Statistiques descriptives"
author: Groupe référents R <br>  Ministère de la Transition écologique et solidaire
  <br> Ministère de la Cohésion des Territoires
date: '`r format(Sys.time(), "%d %B %Y")`'
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book


biblio-style: apalike
link-citations: yes
description: Formation R aux statistiques descriptives





---



# Introduction

## Le parcours de formation

Le parcours de formation proposé est structuré en modules de 2 jours chacun :

- 1 : Socle de base $\Rightarrow$ [support](https://rawgit.com/MTES-MCT/parcours-r/master/Supports_formations/m1_socle/_book/index.html)
- 2 : Préparer ses données avec le tidyverse $\Rightarrow$ [support](https://rawgit.com/MTES-MCT/parcours-r/master/Supports_formations/m2_preparation_donnees/_book/index.html)
- 3 : Statistiques descriptives $\Rightarrow$ [support](https://rawgit.com/MTES-MCT/parcours-r/master/Supports_formations/m3_stats_desc/_book/index.html)
- 4 : Analyses multivariées $\Rightarrow$ [support](https://rawgit.com/MTES-MCT/parcours-r/master/Supports_formations/m4_analyse_donnees/_book/index.html)
- 5 : Datavisualisation : Produire des graphiques, des cartes et des tableaux $\Rightarrow$ [support](https://rawgit.com/MTES-MCT/parcours-r/master/Supports_formations/m5_valorisation_des_donnees/_book/index.html)
- 6 : Documents reproductibles avec RMarkdown (2^ème^ semestre 2019)

... et en perspective : analyse spatiale, applis interactives avec Shiny, big data, etc.

Pour vous tenir au courant de l'offre de formation proposée par le réseau des CVRH, [consultez la plateforme OUPS](http://oups-cmvrh.e2.rie.gouv.fr/). Vous pouvez vous y abonner pour recevoir les annonces qui vous intéressent.

Il existe une liste pour diffuser de l'information, échanger autour de R ou lever des points de blocage. Pour s'insrire, envoyer un message vide avec le titre "subscribe labo.communaute-r" à l'adresse sympa@developpement-durable.gouv.fr.


## Objectif général
Ce qui est visé est une autonomie en matière de statistiques de base avec le logiciel R.

Le module comprend, pour chacune des cinq parties ci-dessous, l’acquisition ou le rappel des notions statistiques abordées, ainsi que la maîtrise de la production et de l'interprétation, avec le logiciel R, des statistiques descriptives, des représentations graphiques et des tests usuels.

## Notions et méthodes présentées

### Analyse univariée d’une variable quantitative

- Histogramme
- Courbe de densité
- Diagramme quantile-quantile
- Statistiques de tendance centrale (moyenne, médiane)
- Statistiques de dispersion (variance, coefficient de variation, intervalle inter-quartiles)
- Méthodes de discrétisation

### Analyse univariée d’une variable qualitative
- Diagrammes en barres et en secteurs
- Tableau de fréquences pondérées ou non pondérées


### Relation entre 2 variables quantitatives
- Nuage de points
- Corrélation paramétrique ou non paramétrique

### Relation entre 2 variables qualitatives
- Graphique en barres empilées ou juxtaposées
- Graphique en mosaïque
- Tableau de contingence
- Profils-lignes et profils-colonnes
- Test du $\chi^2$, V de Cramer

### Relation entre une variable qualitative et une variable quantitative
- Agrégation d’une variable quantitative selon une variable qualitative
- Boxplot, violin plot
- ANOVA


## Fondamentaux R présentés
Objets R, scripts, graphiques avec `ggplot2`, tests avec les packages de `base`, `dplyr` et `lsr`.


