name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main
      - master
jobs:
  call-workflow:
    uses: jdlom/parcours-r/.github/workflows/workflow1.yml@heads/workflow_reutilisable
#70e21495ade811645527734a09862a5d064670fe