# Exercices pour R Studio

## Exercice 1 : Prendre en main RStudio (10 min.)

* Depuis le gestionnaire de fichier de RStudio (panneau bas-droite), vous allez créer un dossier qui va servir de dossier de travail au cours de la formation. Pour cela : utilisez le bouton **New folder** (expl. Formation_R).
* Pour définir ce dossier comme répertoire de travail de R, sélectionnez-le et allez dans le menu **More/Set as working directory**. Regardez ce qui se passe dans la console (panneau bas gauche). Qu'est-ce que cela signifie ?
* Si vous voulez avoir plus de renseignements sur la fonction setwd, vous pouvez utiliser l'aide en ligne de R en écrivant `?setwd` ou `help(setwd)` dans la console. Qu'est ce passe-t-il ?
* Dans l'onglet **Help** de RStudio, vous pouvez également faire une recherche à partir du moteur de recherche. Essayez d'obtenir des informations sur la fonction `dir()`.

## Exercice 2 : Faire ses premiers calculs (15 min.)

* Dans la console, faite des calculs simples : `2 + 3`, `5 * 4`, `5 + (6 * 4)`, `2.5 * 1.3`, `3**3`
* Que se passe-t-il lorsque vous écrivez **pi** dans la console ? Qu'est-ce que cela signifie ?
* Calculez maintenant `cos(pi)` et `sin(pi/2)`. Que voyez-vous apparaître au moment où vous écrivez ces fonctions ?
* Faites maintenant la moyenne des nombres : 4, 5, 2, 1. Avez-vous utilisé un calcul ou une fonction de R ?
* Calculez la valeur absolue de l'opération `2 – 6`.
* Calculez maintenant `round(2.125412)`. Que voyez-vous ? Comment pouvez-vous faire pour faire un arrondi de `2.125412` à deux chiffres après la virgule (vous pouvez utiliser l'aide de R).
* Que se passe-t-il lorsque vous manipulez les flèches haut et bas depuis la console ?

## Exercice 3 : Créer ses premières variables (15 min.)

* Dans la console, créer deux variables numériques a et b de valeur 5 et 4 par assignation : `a<-5` et `b<-4`
* Que se passe-t-il dans le panneau Environement (en haut à droite) ?
* Faites maintenant un calcul avec ces variables comme `a+b` et `a*b`.
* Vous allez ensuite créer une troisième variable à partir d'un calcul sur les deux premières : `c<-a+3*b`
* Vous pouvez afficher la liste des variables avec la fonction `ls()`.
* Modifiez maintenant la valeur de `a` en lui donnant la valeur 10. Vérifiez votre ré-assignation dans la panneau  Environement.
* Créez une variable chaîne de caractère : `t<-'texte'` (vous pouvez également utiliser les doubles quotes comme "texte" mais ne les mélangez pas).
* Concaténez (mettez bout à bout) `a` et `t` avec la fonction `paste(a,t)`. Que constatez-vous ?
* Pour plus de renseignements sur la fonction `paste()`, pensez à utiliser l'aide de R avec `help(paste)`.
* Créez maintenant les variables `A<-15` et `B<-12`. Que voyez-vous dans la panneau Environement ?
* Vous pouvez supprimer la variables A et B en utilisant la fonction `rm()` (utilisez l'aide de R pour avoir plus de renseignements sur la fonction `rm`).

## Exercice 4 : Créer son premier script (20 min.)

* Depuis le panneau d'édition de script de RStudio (en haut à gauche), vous allez créer un script ré-utilisable permettant de calculer l'indice de masse corporelle d'un individu (IMC) et d'afficher le résultat dans la console sous la forme d'un phrase explicite. L'IMC est calculé par la masse sur la taille au carré d'un individu (`masse/taille²`).
* Quelques petits conseils :
     * de façon générale, n'hésitez pas à commenter votre script pour vous aider à le comprendre lorsque vous serez amené à le reprendre,
     * pensez à bien assigner vos variables poids et taille pour une meilleure ré-utilisabilité du script,
     * la fonction print() permet d'afficher une chaîne de caractères dans la console,
     * pensez à arrondir le résultat de votre calcul d'IMC. 
* Enregistrez ensuite votre script dans votre répertoire de travail. L'extension d'un fichier script pour R est .R.